export const GET_PARTY_CONNECTION_PROGRESS = "GET_PARTY_CONNECTION_PROGRESS";
export const GET_PARTY_CONNECTION_SUCCESS = "GET_PARTY_CONNECTION_SUCCESS";
export const GET_PARTY_CONNECTION_ERROR = "GET_PARTY_CONNECTION_ERROR";
